---
# Run tests
name: kyverno-testing

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions: {}

    name: Install Kyverno CLI
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.16.1'
      - name: Check install
        run: kyverno version
      - name: Check CWD
        run: ls -l
      - name: Unit-test policies in test folder
        run: kyverno test test/
